package Vista;

import Modelo.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPCell;
import java.awt.event.KeyEvent;
import java.awt.Desktop;
import java.io.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;

public class Principal extends javax.swing.JFrame {
    Cliente cl = new Cliente();
    Productos prod = new Productos();
    Venta venta = new Venta();
    Detalle detalle = new Detalle();
    Configuracion config = new Configuracion();
    DefaultTableModel modelo = new DefaultTableModel();
    Conexion cn = new Conexion();
    Connection con;
    PreparedStatement ps;
    ResultSet rs;
    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    public void mostrarDatos(DefaultTableModel modelo, String sql){
        limpiarTabla(modelo);
        try{
            con = cn.getConnection();
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            ResultSetMetaData metaData = rs.getMetaData();
            int numCol = metaData.getColumnCount();
            while(rs.next()){
                Object[] fila = new Object[numCol];
                for(int i=0;i<numCol;i++){
                    fila[i] = rs.getObject(i+1);
                }
                modelo.addRow(fila);
            }
        }catch(SQLException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,"Error al conectar");
        }
    }
    
    
    public void limpiarTabla(DefaultTableModel modelo){
        modelo.setRowCount(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        newVentaBtn = new javax.swing.JButton();
        clientesBtn = new javax.swing.JButton();
        productosBtn = new javax.swing.JButton();
        ventasBtn = new javax.swing.JButton();
        configBtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        newVentaPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        tablaNewVenta = new javax.swing.JScrollPane();
        tableVenta = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtdni = new javax.swing.JTextField();
        txtapellido = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        Jlbltotal = new javax.swing.JLabel();
        imprimirBtn = new javax.swing.JButton();
        ingresarBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lbltotal = new javax.swing.JLabel();
        clientesPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        txtdniCliente = new javax.swing.JTextField();
        txtapellidoCliente = new javax.swing.JTextField();
        txtnombreCliente = new javax.swing.JTextField();
        txtcelCliente = new javax.swing.JTextField();
        txtdirCliente = new javax.swing.JTextField();
        txtrazonCliente = new javax.swing.JTextField();
        scrollCliente = new javax.swing.JScrollPane();
        tableCliente = new javax.swing.JTable();
        guardarBtnCliente = new javax.swing.JButton();
        updateBtnCliente = new javax.swing.JButton();
        cancelarBtnCliente = new javax.swing.JButton();
        eliminarbtnCliente = new javax.swing.JButton();
        productosPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        txtcodigoProd = new javax.swing.JTextField();
        txtdescProd = new javax.swing.JTextField();
        txtcantidadProd = new javax.swing.JTextField();
        txtprecioProd = new javax.swing.JTextField();
        tablaProd = new javax.swing.JScrollPane();
        tableProd = new javax.swing.JTable();
        guardarProd = new javax.swing.JButton();
        updateProd = new javax.swing.JButton();
        eliminarProd = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        ventasPanel = new javax.swing.JPanel();
        tablaVentas = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        pdfBtn = new javax.swing.JButton();
        configPanel = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        txtcuitConfig = new javax.swing.JTextField();
        txtnombreConfig = new javax.swing.JTextField();
        txtcelConfig = new javax.swing.JTextField();
        txtdirConfig = new javax.swing.JTextField();
        txtrazonConfig = new javax.swing.JTextField();
        updateBtnConfig = new javax.swing.JButton();
        encabezadoLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 255));

        newVentaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Nventa.png"))); // NOI18N
        newVentaBtn.setText("Nueva Venta");
        newVentaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newVentaBtnActionPerformed(evt);
            }
        });

        clientesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clientes.png"))); // NOI18N
        clientesBtn.setText("Clientes");
        clientesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesBtnActionPerformed(evt);
            }
        });

        productosBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/producto.png"))); // NOI18N
        productosBtn.setText("Productos");
        productosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productosBtnActionPerformed(evt);
            }
        });

        ventasBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/compras.png"))); // NOI18N
        ventasBtn.setText("Ventas");
        ventasBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ventasBtnActionPerformed(evt);
            }
        });

        configBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/config.png"))); // NOI18N
        configBtn.setText("Configuracion");
        configBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(configBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newVentaBtn)
                    .addComponent(productosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ventasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(newVentaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(clientesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(productosBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ventasBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(configBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 600));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        newVentaPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Codigo");

        jLabel4.setText("Cantidad");

        txtcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodigoActionPerformed(evt);
            }
        });

        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });

        tableVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableVenta.setGridColor(new java.awt.Color(255, 255, 255));
        tablaNewVenta.setViewportView(tableVenta);

        jLabel7.setText("Dni");

        jLabel8.setText("Apellido");

        jLabel9.setText("Nombre");

        txtdni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdniActionPerformed(evt);
            }
        });
        txtdni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtdniKeyPressed(evt);
            }
        });

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });

        Jlbltotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        Jlbltotal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/money.png"))); // NOI18N
        Jlbltotal.setText("Total:");

        imprimirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/print.png"))); // NOI18N
        imprimirBtn.setText("Imprimir");
        imprimirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imprimirBtnActionPerformed(evt);
            }
        });

        ingresarBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Carrito-de-compras.png"))); // NOI18N
        ingresarBtn.setText("Ingresar");
        ingresarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingresarBtnActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        jButton2.setText("Quitar Producto");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lbltotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout newVentaPanelLayout = new javax.swing.GroupLayout(newVentaPanel);
        newVentaPanel.setLayout(newVentaPanelLayout);
        newVentaPanelLayout.setHorizontalGroup(
            newVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newVentaPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(newVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newVentaPanelLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(newVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(newVentaPanelLayout.createSequentialGroup()
                                .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newVentaPanelLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(93, 93, 93)
                                .addComponent(jLabel4)
                                .addGap(9, 9, 9)))
                        .addGap(45, 45, 45)
                        .addComponent(ingresarBtn)
                        .addGap(42, 42, 42)
                        .addComponent(jButton2))
                    .addComponent(tablaNewVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(newVentaPanelLayout.createSequentialGroup()
                        .addGroup(newVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(newVentaPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel7)
                                .addGap(89, 89, 89)
                                .addComponent(jLabel8)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel9)
                                .addGap(57, 57, 57))
                            .addGroup(newVentaPanelLayout.createSequentialGroup()
                                .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)))
                        .addComponent(imprimirBtn)
                        .addGap(137, 137, 137)
                        .addComponent(Jlbltotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbltotal)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        newVentaPanelLayout.setVerticalGroup(
            newVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newVentaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ingresarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablaNewVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(newVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newVentaPanelLayout.createSequentialGroup()
                        .addGroup(newVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(newVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(newVentaPanelLayout.createSequentialGroup()
                        .addComponent(imprimirBtn)
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, newVentaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Jlbltotal)
                        .addComponent(lbltotal)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", newVentaPanel);

        clientesPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setText("Dni");

        jLabel13.setText("Apellido");

        jLabel14.setText("Nombre");

        jLabel15.setText("Telefono");

        jLabel16.setText("Direccion");

        jLabel17.setText("Razon social");

        txtdniCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdniClienteActionPerformed(evt);
            }
        });

        txtnombreCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreClienteActionPerformed(evt);
            }
        });

        tableCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dni", "Apellido", "Nombre", "Telefono", "Direccion", "Razon social"
            }
        ));
        tableCliente.setGridColor(new java.awt.Color(255, 255, 255));
        tableCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClienteMouseClicked(evt);
            }
        });
        scrollCliente.setViewportView(tableCliente);

        guardarBtnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarTodo.png"))); // NOI18N
        guardarBtnCliente.setText("Guardar");
        guardarBtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarBtnClienteActionPerformed(evt);
            }
        });

        updateBtnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar (2).png"))); // NOI18N
        updateBtnCliente.setText("Actualizar");
        updateBtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnClienteActionPerformed(evt);
            }
        });

        cancelarBtnCliente.setText("Cancelar");
        cancelarBtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarBtnClienteActionPerformed(evt);
            }
        });

        eliminarbtnCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        eliminarbtnCliente.setText("Eliminar");
        eliminarbtnCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarbtnClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout clientesPanelLayout = new javax.swing.GroupLayout(clientesPanel);
        clientesPanel.setLayout(clientesPanelLayout);
        clientesPanelLayout.setHorizontalGroup(
            clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientesPanelLayout.createSequentialGroup()
                        .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addGap(27, 27, 27)
                        .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdniCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                            .addComponent(txtapellidoCliente)
                            .addComponent(txtnombreCliente)
                            .addComponent(txtcelCliente)
                            .addComponent(txtdirCliente)
                            .addComponent(txtrazonCliente)))
                    .addGroup(clientesPanelLayout.createSequentialGroup()
                        .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(guardarBtnCliente)
                            .addComponent(eliminarbtnCliente))
                        .addGap(18, 18, 18)
                        .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateBtnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelarBtnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 732, Short.MAX_VALUE)
                .addContainerGap())
        );
        clientesPanelLayout.setVerticalGroup(
            clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtdniCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(txtapellidoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(txtnombreCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(txtcelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtdirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtrazonCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(guardarBtnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(updateBtnCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(clientesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eliminarbtnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelarBtnCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61))
            .addGroup(clientesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", clientesPanel);

        productosPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel18.setText("Codigo");

        jLabel19.setText("Descripcion");

        jLabel20.setText("Cantidad");

        jLabel21.setText("Precio");

        tableProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Descripcion", "Precio", "Stock"
            }
        ));
        tableProd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProdMouseClicked(evt);
            }
        });
        tablaProd.setViewportView(tableProd);

        guardarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/GuardarTodo.png"))); // NOI18N
        guardarProd.setText("Guardar");
        guardarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarProdActionPerformed(evt);
            }
        });

        updateProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar (2).png"))); // NOI18N
        updateProd.setText("Actualizar");
        updateProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProdActionPerformed(evt);
            }
        });

        eliminarProd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        eliminarProd.setText("Eliminar");
        eliminarProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarProdActionPerformed(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout productosPanelLayout = new javax.swing.GroupLayout(productosPanel);
        productosPanel.setLayout(productosPanelLayout);
        productosPanelLayout.setHorizontalGroup(
            productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productosPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eliminarProd)
                    .addGroup(productosPanelLayout.createSequentialGroup()
                        .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel18)
                                .addComponent(jLabel19)
                                .addComponent(jLabel20)
                                .addComponent(jLabel21))
                            .addGroup(productosPanelLayout.createSequentialGroup()
                                .addComponent(guardarProd)
                                .addGap(14, 14, 14)))
                        .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(productosPanelLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtcodigoProd, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                                    .addComponent(txtdescProd)
                                    .addComponent(txtcantidadProd)
                                    .addComponent(txtprecioProd)))
                            .addGroup(productosPanelLayout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(updateProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addGap(18, 18, 18)
                .addComponent(tablaProd, javax.swing.GroupLayout.DEFAULT_SIZE, 706, Short.MAX_VALUE)
                .addContainerGap())
        );
        productosPanelLayout.setVerticalGroup(
            productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(productosPanelLayout.createSequentialGroup()
                .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(productosPanelLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(txtcodigoProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtdescProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txtcantidadProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(txtprecioProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardarProd)
                            .addComponent(updateProd))
                        .addGap(18, 18, 18)
                        .addGroup(productosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(eliminarProd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(productosPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(tablaProd, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", productosPanel);

        ventasPanel.setBackground(new java.awt.Color(255, 255, 255));

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Cliente", "Total"
            }
        ));
        tablaVentas.setViewportView(jTable4);

        pdfBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pdf.png"))); // NOI18N
        pdfBtn.setText("PDF");
        pdfBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pdfBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ventasPanelLayout = new javax.swing.GroupLayout(ventasPanel);
        ventasPanel.setLayout(ventasPanelLayout);
        ventasPanelLayout.setHorizontalGroup(
            ventasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventasPanelLayout.createSequentialGroup()
                .addContainerGap(145, Short.MAX_VALUE)
                .addGroup(ventasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ventasPanelLayout.createSequentialGroup()
                        .addComponent(pdfBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventasPanelLayout.createSequentialGroup()
                        .addComponent(tablaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))))
        );
        ventasPanelLayout.setVerticalGroup(
            ventasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ventasPanelLayout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(pdfBtn)
                .addGap(16, 16, 16)
                .addComponent(tablaVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        jTabbedPane1.addTab("", ventasPanel);

        configPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel22.setText("Datos de la Empresa");

        jLabel23.setText("Cuit");

        jLabel24.setText("Nombre");

        jLabel25.setText("Telefono");

        jLabel26.setText("Direccion");

        jLabel27.setText("Razon Social");

        updateBtnConfig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Actualizar (2).png"))); // NOI18N
        updateBtnConfig.setText("Actualizar");
        updateBtnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnConfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout configPanelLayout = new javax.swing.GroupLayout(configPanel);
        configPanel.setLayout(configPanelLayout);
        configPanelLayout.setHorizontalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(configPanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel25))
                            .addComponent(txtcelConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(configPanelLayout.createSequentialGroup()
                                .addGap(185, 185, 185)
                                .addComponent(jLabel23)
                                .addGap(233, 233, 233)
                                .addComponent(jLabel24))
                            .addGroup(configPanelLayout.createSequentialGroup()
                                .addGap(201, 201, 201)
                                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(configPanelLayout.createSequentialGroup()
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel26)
                                        .addGap(153, 153, 153)
                                        .addComponent(jLabel27))
                                    .addGroup(configPanelLayout.createSequentialGroup()
                                        .addComponent(txtdirConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(88, 88, 88)
                                        .addComponent(txtrazonConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(configPanelLayout.createSequentialGroup()
                                .addGap(139, 139, 139)
                                .addComponent(txtcuitConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(107, 107, 107)
                                .addComponent(txtnombreConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 271, Short.MAX_VALUE)))
                .addGap(178, 178, 178))
            .addGroup(configPanelLayout.createSequentialGroup()
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addComponent(updateBtnConfig))
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addGap(400, 400, 400)
                        .addComponent(jLabel22)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        configPanelLayout.setVerticalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel22)
                .addGap(43, 43, 43)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcuitConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnombreConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcelConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdirConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtrazonConfig, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addComponent(updateBtnConfig)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("", configPanel);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 1000, 440));

        encabezadoLbl.setBackground(new java.awt.Color(102, 102, 255));
        encabezadoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/encabezado.png"))); // NOI18N
        getContentPane().add(encabezadoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 1000, 160));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtdniClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdniClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdniClienteActionPerformed

    private void txtnombreClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreClienteActionPerformed

    private void pdfBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pdfBtnActionPerformed
        // TODO add your handling code here:
        int fila = jTable4.getSelectedRow();
        modelo = (DefaultTableModel) jTable4.getModel();
        File file = new File("src/Pdf/detalle_venta"+modelo.getValueAt(fila, 0)+".pdf");
        try {
            Desktop.getDesktop().open(file);
        } catch (IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_pdfBtnActionPerformed

    private void clientesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesBtnActionPerformed
        modelo = (DefaultTableModel) tableCliente.getModel();
        String sql = "Select dni,apellido,nombre,telefono,direccion,razon_social from clientes";
        mostrarDatos(modelo,sql);
        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_clientesBtnActionPerformed

    private void guardarBtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarBtnClienteActionPerformed
        if(!"".equals(txtdniCliente.getText()) && !"".equals(txtnombreCliente.getText()) && 
                !"".equals(txtapellidoCliente.getText())){
            cl.setDni(txtdniCliente.getText());
            cl.setApellido(txtapellidoCliente.getText());
            cl.setNombre(txtnombreCliente.getText());
            cl.setTelefono(txtcelCliente.getText());
            cl.setDireccion(txtdirCliente.getText());
            cl.setRazon(txtrazonCliente.getText());
            cl.registrar();
            JOptionPane.showMessageDialog(null,"Cliente guardado con Exito!!");
        }else{
            JOptionPane.showMessageDialog(null,"Por lo menos Dni, Apellido y Nombre deben estar cargados");
        }
        modelo = (DefaultTableModel) tableCliente.getModel();
        String sql = "Select dni,apellido,nombre,telefono,direccion,razon_social from clientes";
        mostrarDatos(modelo,sql);
    }//GEN-LAST:event_guardarBtnClienteActionPerformed

    private void configBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configBtnActionPerformed
        jTabbedPane1.setSelectedIndex(4); 
        try {
            obtenerConfig();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        txtcuitConfig.setText(config.getCuit());
        txtnombreConfig.setText(config.getNombre());
        txtcelConfig.setText(config.getTelefono());
        txtdirConfig.setText(config.getDireccion());
        txtrazonConfig.setText(config.getRazon());
    }//GEN-LAST:event_configBtnActionPerformed

    private void guardarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarProdActionPerformed
        if(!"".equals(txtcodigoProd.getText())&&!"".equals(txtdescProd.getText())&&
            !"".equals(txtprecioProd.getText())&& !"".equals(txtcantidadProd.getText())){
            prod.setCodigo(txtcodigoProd.getText());
            prod.setDescripcion(txtdescProd.getText());
            prod.setStock(Integer.parseInt(txtcantidadProd.getText()));
            prod.setPrecio(Double.valueOf(txtprecioProd.getText()));
            prod.registrar();
            JOptionPane.showMessageDialog(null,"Producto guardado con Exito!!");
        }else{
            JOptionPane.showMessageDialog(null,"Todos los campos deben estar completos");

        }
        String sql = "select codigo,descripcion,precio,stock_disponible from productos";
        mostrarDatos(modelo,sql);
    }//GEN-LAST:event_guardarProdActionPerformed

    private void productosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productosBtnActionPerformed
        modelo = (DefaultTableModel) tableProd.getModel();
        String sql = "select codigo,descripcion,precio,stock_disponible from productos";
        mostrarDatos(modelo,sql);
        jTabbedPane1.setSelectedIndex(2);
    
    }//GEN-LAST:event_productosBtnActionPerformed
    
    private void tableClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClienteMouseClicked
        
    }//GEN-LAST:event_tableClienteMouseClicked
    public void eliminar(DefaultTableModel modelo,String sql,int fila){
        if(fila!=-1){
            Object id = modelo.getValueAt(fila,0);
            int confirmacion = JOptionPane.showConfirmDialog(null,"¿Está seguro de eliminar este cliente?","Confirmar eliminación",JOptionPane.YES_NO_OPTION);
            if(confirmacion == JOptionPane.YES_OPTION){
                try{
                    con = cn.getConnection();
                    ps = con.prepareStatement(sql);
                    ps.setObject(1,id);
                    int filaAfectada = ps.executeUpdate();
                    if(filaAfectada>0){
                        modelo.removeRow(fila);
                        JOptionPane.showMessageDialog(null, "Fila eliminada correctamente");
                    }else{
                        JOptionPane.showMessageDialog(null, "Error al eliminar la fila de la base de datos");
                    }
                }catch(SQLException e){
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(null, "Error al conectar con la base de datos");
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, selecciona una fila para eliminar");
        }
    }
    
    
    private void newVentaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newVentaBtnActionPerformed
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_newVentaBtnActionPerformed

    private void ventasBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ventasBtnActionPerformed
        jTabbedPane1.setSelectedIndex(3);
        String sql = "select id_venta, concat(nombre,' ',apellido) as nombre_completo, total "
                + "from ventas a inner join clientes b on a.id_cliente=b.id_cliente";
        modelo = (DefaultTableModel) jTable4.getModel();
        mostrarDatos(modelo,sql);
    }//GEN-LAST:event_ventasBtnActionPerformed

    private void eliminarbtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarbtnClienteActionPerformed
        modelo = (DefaultTableModel) tableCliente.getModel();
        String sql = "delete from clientes where dni = ?";   
        int fila = tableCliente.getSelectedRow();
        eliminar(modelo,sql,fila);
    }//GEN-LAST:event_eliminarbtnClienteActionPerformed

    private void eliminarProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarProdActionPerformed
        modelo = (DefaultTableModel) tableProd.getModel();
        String sql = "delete from productos where codigo = ?";
        int fila = tableProd.getSelectedRow();
        eliminar(modelo,sql,fila);
    }//GEN-LAST:event_eliminarProdActionPerformed

    private void cancelarBtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarBtnClienteActionPerformed
        txtdniCliente.setText("");
        txtapellidoCliente.setText("");
        txtnombreCliente.setText("");
        txtcelCliente.setText("");
        txtdirCliente.setText("");
        txtrazonCliente.setText("");
    }//GEN-LAST:event_cancelarBtnClienteActionPerformed

    private void tableProdMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdMouseClicked
                
    }//GEN-LAST:event_tableProdMouseClicked

    private void updateProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProdActionPerformed
        int fila = tableProd.getSelectedRow();
        modelo = (DefaultTableModel) tableProd.getModel();
        String sql2="select id_producto from productos where codigo = ?";
        if(fila!=-1){
            try {
                con = cn.getConnection();
                Object codigo = modelo.getValueAt(fila,0);
                ps = con.prepareStatement(sql2);
                ps.setObject(1, codigo);
                rs = ps.executeQuery();
                if(rs.next()){
                    prod.setId(rs.getInt("id_producto"));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex.toString());
            }
            String sql = "update productos set codigo=?, descripcion=?, precio=?, stock_disponible=? where id_producto=?";
            prod.setCodigo(String.valueOf( modelo.getValueAt(fila,0)));
            prod.setDescripcion(String.valueOf(modelo.getValueAt(fila,1)));
            prod.setPrecio(Double.valueOf(String.valueOf(modelo.getValueAt(fila,2))));
            prod.setStock(Integer.parseInt(String.valueOf( modelo.getValueAt(fila,3))));
            try{
                con = cn.getConnection();
                ps = con.prepareStatement(sql);
                ps.setString(1, prod.getCodigo());
                ps.setString(2, prod.getDescripcion());
                ps.setDouble(3, prod.getPrecio());
                ps.setInt(4, prod.getStock());
                ps.setInt(5, prod.getId());
                ps.execute();
            }catch(SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al actualizar");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
        }
        String sql3 = "select codigo,descripcion,precio,stock_disponible from productos";
        mostrarDatos(modelo,sql3);
    }//GEN-LAST:event_updateProdActionPerformed

    private void updateBtnClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnClienteActionPerformed
        int fila = tableCliente.getSelectedRow();
        modelo = (DefaultTableModel) tableCliente.getModel();
        String sql2="select id_cliente from clientes where dni = ?";
        if(fila!=-1){
            try {
                con = cn.getConnection();
                Object dni = modelo.getValueAt(fila,0);
                ps = con.prepareStatement(sql2);
                ps.setObject(1, dni);
                rs = ps.executeQuery();
                if(rs.next()){
                    cl.setId(rs.getInt("id_cliente"));
                }
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null,ex.toString());
            }
            String sql = "update clientes set dni=?, apellido=?, nombre=?, telefono=?, direccion=?, "
                    + "razon_social=? where id_cliente=?";
            cl.setDni(String.valueOf( modelo.getValueAt(fila,0)));
            cl.setApellido(String.valueOf(modelo.getValueAt(fila,1)));
            cl.setNombre(String.valueOf(modelo.getValueAt(fila,2)));
            cl.setTelefono(String.valueOf( modelo.getValueAt(fila,3)));
            cl.setDireccion(String.valueOf( modelo.getValueAt(fila,4)));
            cl.setRazon(String.valueOf( modelo.getValueAt(fila,5)));
            try{
                con = cn.getConnection();
                ps = con.prepareStatement(sql);
                ps.setString(1, cl.getDni());
                ps.setString(2, cl.getApellido());
                ps.setString(3, cl.getNombre());
                ps.setString(4, cl.getTelefono());
                ps.setString(5, cl.getDireccion());
                ps.setString(6, cl.getRazon());
                ps.setInt(7, cl.getId());
                ps.execute();
            }catch(SQLException e){
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, "Error al actualizar");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar una fila");
        }
        String sql3 = "select dni,apellido,nombre,telefono,direccion,razon_social from clientes";
        mostrarDatos(modelo,sql3);        
    }//GEN-LAST:event_updateBtnClienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        txtcodigoProd.setText("");
        txtdescProd.setText("");
        txtcantidadProd.setText("");
        txtprecioProd.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtdniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdniActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtdniActionPerformed

    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantidadActionPerformed

    private void txtcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodigoActionPerformed
    public double total = 0;
    private void ingresarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingresarBtnActionPerformed
        // TODO add your handling code here:
        String sql = "select * from productos where codigo = ?";
        int cantidad = Integer.parseInt(txtcantidad.getText());
        try{
            con = cn.getConnection();
            ps = con.prepareStatement(sql);
            ps.setString(1, txtcodigo.getText());
            rs = ps.executeQuery();
            if(rs.next()){
                prod.setId(rs.getInt("id_producto"));
                prod.setCodigo(rs.getString("codigo"));
                prod.setDescripcion(rs.getString("descripcion"));
                prod.setPrecio(rs.getDouble("precio"));
                prod.setStock(rs.getInt("stock_disponible"));
            }
            modelo = (DefaultTableModel) tableVenta.getModel();
            Object[] fila = new Object[5];
            fila[0] = prod.getCodigo();
            fila[1] = prod.getDescripcion();
            fila[2] = cantidad;
            fila[3] = prod.getPrecio();
            fila[4] = prod.getPrecio()*cantidad;
            modelo.addRow(fila);
            total = prod.getPrecio()*cantidad + total;
            lbltotal.setText(String.valueOf("$"+total));
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error, Producto inexistente!!");
        }
    }//GEN-LAST:event_ingresarBtnActionPerformed
    double aux = 0;
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int fila = tableVenta.getSelectedRow();
        modelo = (DefaultTableModel) tableVenta.getModel();
        aux = (double) tableVenta.getValueAt(tableVenta.getSelectedRow(), 4);
        total = total - aux;
        modelo.removeRow(fila);
        lbltotal.setText(String.valueOf("$"+total));
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtdniKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtdniKeyPressed
        String dni = txtdni.getText();
        String sql = "select * from clientes where dni = ?";
        if(!"".equals(txtdni.getText())){
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            try{
                con = cn.getConnection();
                ps = con.prepareStatement(sql);
                ps.setString(1, dni);
                rs = ps.executeQuery();
                if(rs.next()){
                    cl.setId(rs.getInt("id_cliente"));
                    cl.setDni(rs.getString("dni"));
                    cl.setApellido(rs.getString("apellido"));
                    cl.setNombre(rs.getString("nombre"));
                    cl.setTelefono(rs.getString("telefono"));
                    cl.setDireccion(rs.getString("direccion"));
                    cl.setRazon(rs.getString("razon_social"));
                }
                txtapellido.setText(cl.getApellido());
                txtnombre.setText(cl.getNombre());
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null,e.toString());
            }
            if(cl.getNombre() == null){
                JOptionPane.showMessageDialog(null,"Dni ingresado inexistente!");
            }
            
            }
        }
        
    }//GEN-LAST:event_txtdniKeyPressed
    
    public void obtenerIdVenta(){
        LocalDate ahora = LocalDate.now();
        String fechaForm = ahora.format(DateTimeFormatter.ISO_LOCAL_DATE);
        String sql="select id_venta from ventas where id_cliente="+cl.getId()+" and total="+total+" "
                + "and fecha like'"+fechaForm+"%'";
        try{
            con = cn.getConnection();
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            if(rs.next()){
                venta.setId(rs.getInt("id_venta"));
            }            
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null,e.toString());
        }
        
    }
    private void imprimirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imprimirBtnActionPerformed
        String sql= "insert into ventas(id_cliente,id_configuracion,total)values(?,?,?)";
        try{
            con = cn.getConnection();
            ps = con.prepareStatement(sql);
            ps.setInt(1, cl.getId());
            ps.setInt(2, 1);
            ps.setDouble(3, total);
            ps.execute();
            for(int i=0;i<tableVenta.getRowCount();i++){
                String cod = tableVenta.getValueAt(i, 0).toString();  
                ps = con.prepareStatement("Select id_producto from productos where codigo = ?");
                ps.setString(1, cod);
                rs = ps.executeQuery();
                if(rs.next()){
                    detalle.setId_prod(rs.getInt("id_producto"));
                    ps = con.prepareStatement("update productos set stock_disponible = stock_disponible-? where id_producto=?");
                    ps.setInt(1, (int) tableVenta.getValueAt(i, 2));
                    ps.setInt(2, detalle.getId_prod());
                    ps.execute();
                }
                detalle.setCantidad((int)tableVenta.getValueAt(i, 2));
                detalle.setPrecio((double) tableVenta.getValueAt(i,3));
                detalle.setTotal((double) tableVenta.getValueAt(i, 4));
                obtenerIdVenta();
                detalle.setId_venta(venta.getId());
                
               ps = con.prepareStatement("insert into detalles_venta(id_venta,id_producto,cantidad,precio_unitario,total) "
                       + "values (?,?,?,?,?)");
               ps.setInt(1, detalle.getId_venta());
               ps.setInt(2, detalle.getId_prod());
               ps.setInt(3, detalle.getCantidad());
               ps.setDouble(4, detalle.getPrecio());
               ps.setDouble(5, detalle.getTotal());
               ps.execute();
            }
            JOptionPane.showMessageDialog(null, "Venta realizada exitosamente!!");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e.toString());
        }
        try {
            pdf();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_imprimirBtnActionPerformed

    private void updateBtnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnConfigActionPerformed
        // TODO add your handling code here:
        config.setCuit(txtcuitConfig.getText());
        config.setNombre(txtnombreConfig.getText());
        config.setTelefono(txtcelConfig.getText());
        config.setDireccion(txtdirConfig.getText());
        config.setRazon(txtrazonConfig.getText());
        String sql = "update configuracion_empresa set cuit=?,nombre=?,telefono=?,"
                + "direccion=?,razon_social=?";
        try {
            con = cn.getConnection();
            ps = con.prepareStatement(sql);
            ps.setString(1, config.getCuit());
            ps.setString(2, config.getNombre());
            ps.setString(3, config.getTelefono());
            ps.setString(4, config.getDireccion());
            ps.setString(5, config.getRazon());
            ps.execute();
            JOptionPane.showMessageDialog(null, "Datos guardados correctamente");
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_updateBtnConfigActionPerformed

    public void obtenerConfig() throws SQLException{
        String sql = "select * from configuracion_empresa";
        con = cn.getConnection();
        ps = con.prepareStatement(sql);
        rs = ps.executeQuery();
        if(rs.next()){
            config.setId(rs.getInt("id_configuracion"));
            config.setCuit(rs.getString("cuit"));
            config.setNombre(rs.getString("nombre"));
            config.setTelefono(rs.getString("telefono"));
            config.setDireccion(rs.getString("direccion"));
            config.setRazon(rs.getString("razon_social"));
        }
    }
    public void pdf() throws SQLException {
        try{
            FileOutputStream archivo;
            File file = new File("src/Pdf/detalle_venta"+venta.getId()+".pdf");
            archivo = new FileOutputStream(file);
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            Image im = Image.getInstance("src/Imagenes/logo_pdf.png");
            Paragraph fecha = new Paragraph();
            Font negrita = new Font(Font.FontFamily.TIMES_ROMAN,12,Font.BOLD,BaseColor.BLUE);
            fecha.add(Chunk.NEWLINE);
            LocalDate fechaActual = LocalDate.now();
            fecha.add("Factura: "+venta.getId()+"Fecha: "+ new SimpleDateFormat("dd-mm-yyyy").format(
                    Date.valueOf(fechaActual))+"\n\n");
            PdfPTable encabezado = new PdfPTable(4);
            encabezado.setWidthPercentage(100);
            encabezado.getDefaultCell().setBorder(0);
            float[] columnaEncabezado = new float[]{20f,30f,70f,40f};
            encabezado.setWidths(columnaEncabezado);
            encabezado.setHorizontalAlignment(Element.ALIGN_LEFT);
            encabezado.addCell(im);
            String ciudad = "San Miguel de Tucumán";
            obtenerConfig();
            encabezado.addCell("");
            encabezado.addCell("Cuit: "+config.getCuit()+"\nNomre: "+config.getNombre()+"\nTelefono: "+config.getTelefono()
            +"\nCiudad: "+ciudad+"\nDireccion: "+config.getDireccion());
            encabezado.addCell(String.valueOf(fechaActual));
            doc.add(encabezado);
            //clientes
            Paragraph cliente = new Paragraph();
            cliente.add(Chunk.NEWLINE);
            cliente.add("Datos de los clientes"+"\n\n");
            doc.add(cliente);
            PdfPTable tableC = new PdfPTable(4);
            tableC.setWidthPercentage(100);
            tableC.getDefaultCell().setBorder(0);
            float[] columnaCliente = new float[]{20f,50f,30f,40f};
            tableC.setWidths(columnaCliente);
            tableC.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell cl1 = new PdfPCell(new Phrase("Dni",negrita));
            PdfPCell cl2 = new PdfPCell(new Phrase("Nombre y Apellido",negrita));
            PdfPCell cl3 = new PdfPCell(new Phrase("Telefono",negrita));
            PdfPCell cl4 = new PdfPCell(new Phrase("Direccion",negrita));
            cl1.setBorder(0);
            cl2.setBorder(0);
            cl3.setBorder(0);
            cl4.setBorder(0);
            tableC.addCell(cl1);
            tableC.addCell(cl2);
            tableC.addCell(cl3);
            tableC.addCell(cl4);
            tableC.addCell(cl.getDni());
            tableC.addCell(cl.getNombre()+" "+cl.getApellido());
            tableC.addCell(cl.getTelefono());
            tableC.addCell(cl.getDireccion());
            doc.add(tableC);
            //productos
            Paragraph producto = new Paragraph();
            producto.add(Chunk.NEWLINE);
            producto.add("Detalles de la Venta"+"\n\n");
            doc.add(producto);
            
            PdfPTable tableP = new PdfPTable(4);
            tableP.setWidthPercentage(100);
            tableP.getDefaultCell().setBorder(0);
            float[] columnaProd = new float[]{10f,50f,15f,20f};
            tableP.setWidths(columnaProd);
            tableP.setHorizontalAlignment(Element.ALIGN_LEFT);
            PdfPCell p1 = new PdfPCell(new Phrase("Cant.",negrita));
            PdfPCell p2 = new PdfPCell(new Phrase("Descripcion",negrita));
            PdfPCell p3 = new PdfPCell(new Phrase("Precio U.",negrita));
            PdfPCell p4 = new PdfPCell(new Phrase("Total",negrita));
            p1.setBorder(0);
            p2.setBorder(0);
            p3.setBorder(0);
            p4.setBorder(0);
            tableP.addCell(p1);
            tableP.addCell(p2);
            tableP.addCell(p3);
            tableP.addCell(p4);
            for(int i=0;i<tableVenta.getRowCount();i++){
                tableP.addCell(tableVenta.getValueAt(i,2).toString());
                tableP.addCell(tableVenta.getValueAt(i,1).toString());
                tableP.addCell("$"+tableVenta.getValueAt(i, 3).toString());
                tableP.addCell("$"+tableVenta.getValueAt(i,4).toString());
            }
            doc.add(tableP);
            
            Paragraph info = new Paragraph();
            info.add(Chunk.NEWLINE);
            info.add("Total a Pagar: $"+total);
            info.setAlignment(Element.ALIGN_CENTER);
            doc.add(info);
            
            Paragraph firma = new Paragraph();
            firma.add(Chunk.NEWLINE);
            firma.add("Firma\n\n");
            firma.add("--------------------");
            firma.setAlignment(Element.ALIGN_CENTER);
            doc.add(firma);
            
            doc.close();
            archivo.close();
        } catch (DocumentException | IOException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Jlbltotal;
    private javax.swing.JButton cancelarBtnCliente;
    private javax.swing.JButton clientesBtn;
    private javax.swing.JPanel clientesPanel;
    private javax.swing.JButton configBtn;
    private javax.swing.JPanel configPanel;
    private javax.swing.JButton eliminarProd;
    private javax.swing.JButton eliminarbtnCliente;
    private javax.swing.JLabel encabezadoLbl;
    private javax.swing.JButton guardarBtnCliente;
    private javax.swing.JButton guardarProd;
    private javax.swing.JButton imprimirBtn;
    private javax.swing.JButton ingresarBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lbltotal;
    private javax.swing.JButton newVentaBtn;
    private javax.swing.JPanel newVentaPanel;
    private javax.swing.JButton pdfBtn;
    private javax.swing.JButton productosBtn;
    private javax.swing.JPanel productosPanel;
    private javax.swing.JScrollPane scrollCliente;
    private javax.swing.JScrollPane tablaNewVenta;
    private javax.swing.JScrollPane tablaProd;
    private javax.swing.JScrollPane tablaVentas;
    private javax.swing.JTable tableCliente;
    private javax.swing.JTable tableProd;
    private javax.swing.JTable tableVenta;
    private javax.swing.JTextField txtapellido;
    private javax.swing.JTextField txtapellidoCliente;
    private javax.swing.JTextField txtcantidad;
    private javax.swing.JTextField txtcantidadProd;
    private javax.swing.JTextField txtcelCliente;
    private javax.swing.JTextField txtcelConfig;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcodigoProd;
    private javax.swing.JTextField txtcuitConfig;
    private javax.swing.JTextField txtdescProd;
    private javax.swing.JTextField txtdirCliente;
    private javax.swing.JTextField txtdirConfig;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtdniCliente;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombreCliente;
    private javax.swing.JTextField txtnombreConfig;
    private javax.swing.JTextField txtprecioProd;
    private javax.swing.JTextField txtrazonCliente;
    private javax.swing.JTextField txtrazonConfig;
    private javax.swing.JButton updateBtnCliente;
    private javax.swing.JButton updateBtnConfig;
    private javax.swing.JButton updateProd;
    private javax.swing.JButton ventasBtn;
    private javax.swing.JPanel ventasPanel;
    // End of variables declaration//GEN-END:variables
}
